apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-system-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-system-test
  template:
    metadata:
      labels:
        app: voting-system-test
    spec:
      containers:
        - name: voting-system-test
          image: registry.digitalocean.com/escrow-mobileapp-registry/voting-system-test:{{IMAGE_TAG}}
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: voting-system-db
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: voting-system-db
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: voting-system-db
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: voting-system-db
                  key: DB_NAME
          resources:
            requests:
              memory: "150Mi"
            limits:
              memory: "300Mi"
